---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3261710467-h5F0K9wReFc4pcMcHKMc0m50IfgQ6VErh7CVpvG
:access_token_secret: UYZidkTpTKbPPkrDTCF5Xq18VrCfnSFkGSVMR4clwUIpv
